syntax = "proto3";

package Jubo.JuLiao.IM.Wx.Proto;

// 布尔配置消息
message BoolConfigMessage {
  string Key = 1;    // 键
  bool Value = 2;    // 值
  string Name = 3;   // 名称
  string Desc = 4;   // 描述
}

// 整数配置消息
message IntConfigMessage {
  string Key = 1;    // 键
  int32 Value = 2;   // 值
  string Name = 3;   // 名称
  string Desc = 4;   // 描述
}

// 字符串配置消息
message StrConfigMessage {
  string Key = 1;    // 键
  string Value = 2;  // 值
  string Name = 3;   // 名称
  string Desc = 4;   // 描述
}

message SetConfigTaskMessage {
  string IMEI = 1;
  string WeChatId = 2;
  repeated BoolConfigMessage BoolConfs = 7;
  repeated IntConfigMessage IntConfs = 8;
  repeated StrConfigMessage StrConfs = 9;
}
